# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "1b736a00-04aa-4ea1-a4fb-41cff53ee93a"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app

 # upload to Testflight
  increment_build_number(

    build_number: latest_testflight_build_number + 1,
    xcodeproj: "TaxiManager.xcodeproj"
  )

  changelog = prompt(
    text: "Changelog: ",
    multi_line_end_keyword: "END"
  )

  gym(
    scheme: "TaxiManager",
    export_method: "app-store"
  )

 

  pilot(skip_waiting_for_build_processing: true)

end
